from .news import *
from .user import *
from .group import *
from .contact import *
from .faq import *
from .resources import *
from .puzzles import *
from .home import *
from .submission import *
from .score_challenge import *
from .metrics import *
