# Generated by Django 2.2.6 on 2019-11-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='long_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='short_description',
            new_name='title',
        ),
    ]
