# Generated by Django 2.2.9 on 2020-01-21 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesmodel',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
