# Generated by Django 2.2.7 on 2019-11-19 00:08

from django.db import migrations
import rnapuzzles.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', rnapuzzles.models.user.UserManager()),
            ],
        ),
    ]
