# Generated by Django 2.2.7 on 2020-01-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='code',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
