# Generated by Django 2.2.7 on 2019-12-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'organizer'), (2, 'participant')]),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
