# Generated by Django 2.2.9 on 2020-01-08 09:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0002_remove_customuser_user_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=1, editable=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(verbose_name='Opening date')),
                ('end_date', models.DateField(verbose_name='Closing date')),
                ('current_status', models.IntegerField(choices=[(0, 'Created'), (1, 'Open'), (2, 'Under modeling'), (3, 'Evaluated'), (4, 'Completed')], editable=False)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-puzzle_info', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PuzzleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Maximum 250 characters.', max_length=250, verbose_name='Description')),
                ('sequence', models.TextField(verbose_name="RNA sequence (5' to 3')")),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='Target 3D structure publication date')),
                ('reference', models.CharField(blank=True, help_text='Maximum 500 characters.', max_length=500, verbose_name='Reference')),
                ('reference_url', models.URLField(blank=True, verbose_name='Reference URL')),
                ('pdb_id', models.CharField(blank=True, help_text='Maximum 4 characters (by PDB ID convention).', max_length=4, verbose_name='PDB ID')),
                ('pdb_url', models.URLField(blank=True, verbose_name='PDB URL')),
                ('pdb_file', models.FileField(blank=True, help_text='Allowed types: .pdb, .cif', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdb', 'cif'])], verbose_name='Target 3D structure file')),
                ('img', models.ImageField(blank=True, help_text='Allowed file types: .jpg, .png', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])], verbose_name='Target 3D structure graphic representation')),
            ],
            options={
                'verbose_name': 'Puzzle Information',
            },
        ),
        migrations.CreateModel(
            name='ChallengeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, help_text='Information about file content. Maximum 50 characters.', max_length=50)),
                ('file', models.FileField(blank=True, upload_to='')),
                ('challenge', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='rnapuzzles.Challenge')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='puzzle_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rnapuzzles.PuzzleInfo'),
        ),
    ]
