# Generated by Django 2.2.7 on 2020-01-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0002_metric_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='error_msg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[(0, 'Submitted'), (1, 'Waiting'), (2, 'Error'), (3, ' Success')], default='SB', max_length=2),
        ),
    ]
