# Generated by Django 2.2.7 on 2020-01-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0002_auto_20200128_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='alligment',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
