# Generated by Django 2.2.9 on 2020-01-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0002_resourcesmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='is_automatic',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
