# Generated by Django 2.2.7 on 2019-12-13 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0002_auto_20191207_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rnapuzzles.Group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'organizer'), (2, 'participant'), (3, 'group leader')]),
        ),
    ]
