# Generated by Django 2.2.6 on 2019-11-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0002_auto_20191103_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='NewsModel',
        ),
    ]
