# Generated by Django 2.2.9 on 2020-01-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0002_auto_20200125_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-puzzle_info', '-created_at'], 'permissions': [('metrics_challenge', 'Run computation of metrics')]},
        ),
        migrations.AddField(
            model_name='challenge',
            name='alignment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='challenge',
            name='notification_email_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='alignment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_automatic',
            field=models.DateTimeField(verbose_name='Closing date for server category'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateTimeField(verbose_name='Closing date for human category'),
        ),
    ]
