# Generated by Django 2.2.7 on 2019-12-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0003_auto_20191213_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_group_leader',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
