# Generated by Django 2.2.9 on 2020-01-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0003_score_is_automatic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='is_automatic',
        ),
        migrations.AddField(
            model_name='submission',
            name='is_automatic',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
