# Generated by Django 2.2.9 on 2020-01-30 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0003_auto_20200130_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='member_authorized',
        ),
        migrations.AddField(
            model_name='faqmodel',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
