# Generated by Django 2.2.7 on 2020-01-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0003_submission_alligment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='alligment',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
