# Generated by Django 2.2.9 on 2020-01-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0003_auto_20200108_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': [('name_group', 'Can change the name of the Group'), ('contact_group', 'Can change the contact of the Group'), ('description_group', 'Can change the contact of the Group'), ('accept_group', 'Can accept user for specific group')]},
        ),
    ]
