# Generated by Django 2.2.6 on 2019-11-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0003_auto_20191103_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
