# Generated by Django 2.2.6 on 2019-11-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0004_auto_20191103_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
