# Generated by Django 2.2.9 on 2020-01-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0004_auto_20200121_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Submitted'), (1, 'Waiting'), (2, 'Error'), (3, ' Success')], default=0),
        ),
    ]
