# Generated by Django 2.2.7 on 2019-12-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0004_customuser_is_group_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_group_leader',
        ),
    ]
