# Generated by Django 2.2.7 on 2020-01-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0004_auto_20200128_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='alligment',
            new_name='alignment',
        ),
    ]
