# Generated by Django 2.2.9 on 2020-01-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0005_auto_20200121_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='label',
            field=models.CharField(default='label', max_length=10),
            preserve_default=False,
        ),
    ]
