# Generated by Django 2.2.7 on 2020-01-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0005_auto_20200128_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='alignment',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
