# Generated by Django 2.2.9 on 2020-01-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0006_submission_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='error_msg',
        ),
        migrations.AddField(
            model_name='submission',
            name='msg',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
