# Generated by Django 2.2.7 on 2020-01-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0006_challenge_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='alignment',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
