# Generated by Django 2.2.9 on 2020-01-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0007_auto_20200124_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='msg',
            field=models.TextField(blank=True),
        ),
    ]
