# Generated by Django 2.2.7 on 2020-01-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnapuzzles', '0007_auto_20200128_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='notification_email_send',
            field=models.BooleanField(default=False),
        ),
    ]
