
# deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: rnapuzzles-django
  labels:
    app.kubernetes.io/name: rnapuzzles-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rnapuzzles-django
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rnapuzzles-django
    spec:
       initContainers:
       - name: migrate
         image: "luki4824/rnapuzzles:latest"
         imagePullPolicy: IfNotPresent
         command: ["python", "manage.py", "migrate"]
         env:
           - name: SECRET_KEY
             valueFrom:
                secretKeyRef:
                 name: rnapuzzles-env
                 key: SECRET_KEY
           - name: DB_NAME
             valueFrom:
               secretKeyRef:
                 name: rnapuzzles-env
                 key: DB_NAME
           - name: DB_USER
             valueFrom:
               secretKeyRef:
                 name: rnapuzzles-env
                 key: DB_USER
           - name: DB_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: rnapuzzles-env
                 key: DB_PASSWORD
           - name: DB_HOST
             valueFrom:
               secretKeyRef:
                 name: rnapuzzles-env
                 key: DB_HOST
       containers:
         - name: rnapuzzles
           image: "luki4824/rnapuzzles:latest"
           imagePullPolicy: "Always"
           env:
           - name: SECRET_KEY
             valueFrom:
                secretKeyRef:
                 name: rnapuzzles-env
                 key: SECRET_KEY
           - name: DB_NAME
             valueFrom:
               secretKeyRef:
                 name: rnapuzzles-env
                 key: DB_NAME
           - name: DB_USER
             valueFrom:
               secretKeyRef:
                 name: rnapuzzles-env
                 key: DB_USER
           - name: DB_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: rnapuzzles-env
                 key: DB_PASSWORD
           - name: DB_HOST
             valueFrom:
               secretKeyRef:
                 name: rnapuzzles-env
                 key: DB_HOST
           - name: GUNICORN_CMD_ARGS
             value: "--bind=0.0.0.0:3000 --workers=2 --log-level=debug"

