apiVersion: v1
kind: Service
metadata:
  name: ngnix
  labels:
    app: rnapuzzles-ngnix
spec:
  type: LoadBalancer  
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: rnapuzzles-ngnix
    
