apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3000
      name: first
    - port: 8000
      targetPort: 8000
      name: second
    - port: 8001
      targetPort: 8001
      name: second3
  selector:
    app.kubernetes.io/name: rnapuzzles-django
    
