apiVersion: v1    
kind: Secret
metadata:
 name: rnapuzzles-env
type: Opaque
stringData:
 SECRET_KEY  : "m7$0i2x2oqv%#gi5!6j*&k^sg5@djo(2f0!j^#*upn!+v-k7vy"
 DEBUG  : "0"
 DB_NAME  : rna
 DB_USER  : postgres
 DB_PASSWORD  : password
 DB_HOST  : postgres-postgresql
 DB_PORT  : "5432"

 RABBITMQ_USER  : user
 RABBITMQ_PASSWORD  : password
 RABBITMQ_HOST  : rabbitmq-rabbitmq-ha
 RABBITMQ_PORT  : "5672"
