kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding-postgresql
  namespace: rnapuzzles
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: tiller-helm
roleRef:
  kind: Role
  name: tiller-manager-postgresql
  apiGroup: rbac.authorization.k8s.io