kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager-postgresql
  namespace: postgresql
rules:
- apiGroups: ["", "batch", "extensions", "apps", "rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

